### ISSUE TITLE
boxdestroyer not working 

### ISSUE THREAD

**Issue by charliet26** [svanheulen/boxdestroyer-windower-addon#7]
hi i have been having trouble with boxdestroyer since the last update it does not seem to be able to work out the possibilities, any idea how i can get it working again??

**Comment by svanheulen** [comment]
I don't play any more, you're going to have to give me more information about what's happening. Are there any error messages?

**Comment by charliet26** [comment]
Hi thanks for replying, it comes up with the message: boxdestroyer: lua runtime error: boxdestroyer/boxdestroyer.lua:119: bad argument #1 to 'format' (number expected, got nil)

Sent from my Sony Xperia™ smartphone

---- Seth VanHeulen wrote ----

**Comment by svanheulen** [comment]
Hmmm, seems like a weird place to get an error, but most likely the problem is the `messages.lua` file. The message IDs can change with updates some times so that file needs to be regenerated. If you look in the messages folder in this repo, there's a Python script for doing just that. Can you give that a try and let me know if that fixes it?

**Comment by charliet26** [comment]
how do I go about doing that? never used a python script before,

**Comment by svanheulen** [comment]
Download and install Python 3.5 from https://www.python.org/
Then run the script from the command line like this:
`C:\Python35\python.exe make_messages.py`

**Comment by charliet26** [comment]
that command line comes up with a syntax error at the first colon, C:\

**Comment by svanheulen** [comment]
Oh... uh, it's been way too long since I've used Windows. Maybe Python registers the file type... try just double clicking the script to run it...?

**Comment by charliet26** [comment]
its ok  python is making my head hurt, thanks for the help but think I'm just gonna give up lol 

Date: Mon, 30 Nov 2015 11:17:18 -0800

**Comment by svanheulen** [comment]
Sorry I couldn't help :(
If you know anyone else that uses it and might be able to figure out Python, direct them here. If I can get someone to make the new `messages.lua` file, I'll add it to the official Windower repo so that everyone will get it.

**Comment by talran** [comment]
I think I did it right, took a while to find some boxes to test on but 3/3 tested fine parsing the messages.

**Comment by svanheulen** [comment]
Thanks @talran!
I'll send it to the official Windower but I'm not sure how long it will be before it shows up in the client so, @charliet26, just grab the `messages.lua` file from here and replace the one in the addon's folder.

**Comment by charliet26** [comment]
Great thanks :-) 

Sent from my Sony Xperia™ smartphone

---- Seth VanHeulen wrote ----
